### ISSUE TITLE
Values of hasFeatureType use wrong place type URIs (extra /plone in URI path)

### ISSUE THREAD

**Issue by rybesh** [isawnyu/pleiades-gazetteer#518] opened 2024-09-23 01:24 UTC
In the RDF datasets, values of `pleiades:hasFeatureType` have URIs with an extra `/plone` at the start of the path, like:

```text
https://pleiades.stoa.org//plone/vocabularies/place-types/villa
```

They should be like:

```text
https://pleiades.stoa.org/vocabularies/place-types/villa
```

This currently breaks SPARQL joins between places and their type concepts.

**Comment by paregorios** [comment] 2024-09-27 18:37
The problem is currently only manifest in the bulk download in TTL format, generated weekly on Sundays and obtained via https://atlantides.org/downloads/pleiades/rdf/:

```
ggrep plone *.ttl | more
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/port>,
errata.ttl:        <https://pleiades.stoa.org//plone/vocabularies/place-types/settlement>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/unknown>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/road>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/road>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/villa>;
```

**In evaluating any fix,** we should check for these problems not only in the bulk TTL format, but also in both of the individual place-level RDF serializations where the problem is not currently found:
- Turtle format, for example: https://pleiades.stoa.org/places/59983/turtle
- RDF+XML format, for example: https://pleiades.stoa.org/places/59983/rdf

**Comment by jessesnyder** [comment] 2024-10-08 23:39
@paregorios I regenerated the full archive on staging the way it's generated "in the wild" (via cron), and I think it's looking good. I have not tested the per-Place rdf download, but I didn't find any common code paths, so I think that will be OK (but please test!)

[pleiades-latest.tar.gz](https://github.com/user-attachments/files/17300169/pleiades-latest.tar.gz)

**Comment by paregorios** [comment] 2024-10-09 18:43
@jessesnyder can you double-check that the gzipped tar file you attached above is the result of the latest staging run with modified code? I'm still seeing `/plone/` in it:

```
grep plone *.ttl | more
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/province>;
errata.ttl:    pleiades:hasFeatureType <https://pleiades.stoa.org//plone/vocabularies/place-types/port>,
```

and so on across all `.ttl` files containing `hasFeatureType`

**Comment by jessesnyder** [comment] 2024-10-09 20:16
@paregorios The archive does indeed not contain the files I expected it to contain. Not sure what happened. Running the cron task again now.

**Comment by jessesnyder** [comment] 2024-10-09 21:30
OK @paregorios, take 2:
[pleiades-20241009.tar.gz](https://github.com/user-attachments/files/17318892/pleiades-20241009.tar.gz)

**Comment by paregorios** [comment] 2024-10-09 21:34
@jessesnyder that's got it! And the individual serializations are still fine too. Please merge, wrap, ship, refrigerate, and deploy to production.

**Comment by jessesnyder** [comment] 2024-10-09 21:56
Deployed 🚀

**Comment by paregorios** [comment] 2024-10-14 15:25
This is fixed in the weekly export on 10/13. Closing as resolved.

**Closed as completed** 2024-10-14 15:25 UTC
Labels: bug, priority: high, needs estimate
