### ISSUE TITLE
extra files in pleiades_gis_data.zip

### ISSUE THREAD

**Issue by lahosken** [isawnyu/pleiades-gazetteer#503] opened 2023-10-01 00:14 UTC
Following directions at https://atlantides.org/downloads/pleiades/gis/ ,
I downloaded https://atlantides.org/downloads/pleiades/gis/pleiades_gis_data.zip

When I unzipped it, I expected to get one batch of files; instead I got three.
I got a tree of files in data and another two in Users/paregorios/Documents/files/

I ?guess? someone wanted to create a new .zip but instead appended files to an existing zip?
Maybe will clarify things, maybe will muddy things: here are the files named `names.csv` that I got; note different creation dates.

```$ find data/ Users/ -name 'names.csv' | xargs ls -l
-rw-r--r-- 1 lah lah 7749621 Aug 30  2022 data/gis/names.csv
-rw-r--r-- 1 lah lah 8037250 Sep 29 05:45 Users/paregorios/Documents/files/p/pleiades.datasets/data/gis/names.csv
-rw-r--r-- 1 lah lah 7881639 Mar 29  2023 Users/paregorios/Documents/files/P/pleiades.datasets/data/gis/names.csv
```

**Comment by paregorios** [comment] 2023-10-02 13:01
This is a mess. Thanks for reporting it @lahosken, I'll look into it and get it fixed.

**Comment by paregorios** [comment] 2023-10-02 14:26
This is fixed with https://github.com/isawnyu/pleiades.datasets/commit/610dd03f1229b1fc6ed163316f05713b701f7f15. A prior "upgrade" to the generation script was failing to use indirect paths in the zip file. With my apologies for the confusion and delay caused by the bug, __all users should download today's version (or later) of the zip file data to ensure you are working with the latest files in `data`__. 

Thanks to @lahosken for spotting and reporting this bug.

**Closed as completed by paregorios** 2023-10-02 14:26 UTC
Labels: bug, priority: high, data
