### ISSUE TITLE
Update "time period" field instructions in "default" tab for Location edit page

### ISSUE THREAD

**Issue by atomrab** [isawnyu/pleiades-gazetteer#307] opened 2017-05-18 17:48 UTC
Currently the brief user instructions for the "time period and confidence level" input area read "Select time period for which this name is attested". Presumably this sentence should be changed to reflect the separation of location and name. This also requires an editorial decision about what we want the temporal value(s) for a location to reflect: its initial occupation/use? the full temporal extent during which some human activity took place at that location? the creation or use-dates of the place with which the location is connected? the full temporal extent during which remains were visible/the place was known to human groups?

Example: what are the dates of "Imagery location of the Athenian Treasury at Delphi" (https://pleiades.stoa.org/places/707804475/athenian-treasury/)? Are they a) the Archaic period (when construction began); b) the Classical period (when construction finished); c) the Archaic-Classical periods (when Athens was actively sponsoring it); d) the Classical-Late Antique periods (when the building was in use as a treasury); or c) the Classical-Late Antique AND modern periods, when the building was in use as a treasury and when it was rediscovered and reconstructed as a heritage monument?

**Comment by paregorios** [comment] 2019-03-22 21:28
priority:high because this confuses users and leads to potential task failure

**Comment by paregorios** [comment] 2019-03-25 20:27
duplicate of #339. Closing in favor of that one.

**Closed as completed by paregorios** 2019-03-25 20:27 UTC
Labels: bug, enhancement, priority: high, storify
