### ISSUE TITLE
Insufficient privileges to create connections

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#196] opened 2016-08-01 17:44 UTC
Since Pleiades' connection tool became a standalone one (as opposed to being incorporated into the place-level page), I have been unable to create new connections. Attempts to creat connections result not in a numbered error message, but in a banner that indicates insufficient privileges to complete the operation. However, I experienced differing behavior today. I document two instances below:

**Instasce 1 - unsuccessful attempt to create connection**

For example, if I try to establish a hierarchical connection between this place resource (http://pleiades.stoa.org/places/590099) and this one (http://pleiades.stoa.org/places/590031), I am told "Insufficient Privileges. You do not have sufficient privileges to view this page. If you believe you are receiving this message in error, contact the site administration."

**Instasce 2 - partially successful (?) attempt to create connection**

As a second case, I tried to create a connection between this place resource (http://pleiades.stoa.org/places/93042695) and this one (http://pleiades.stoa.org/places/347468514). This time I did not receive the insufficient privileges message, but the connection seems to have gone through, though now I only see it as a drafting state item that I cannot edit or submit for review.

I tried to be thorough here, let me know if further clarification is required. Thank you!

cc also @paregorios , who was part of the discussion about this one in email.

**Comment by serviliusahala** [comment] 2016-08-18 13:22
If I may update my original trouble ticket - it would seem to me that my difficulties in creating connections seem tied to whether the place resource is recent or not. I was able to create a connection for a newly created place resource (http://pleiades.stoa.org/places/158081395) with no difficulty, while I still encounter difficulty making connections for older place resources. Not certain if this helps in troubleshooting, but I thought I'd add it anyway. Thanks.

**Comment by alecpm** [comment] 2016-08-21 00:28
I'm having a little trouble tracking this down, but I've found something interesting. If I login as a non-Admin Editor user and simply visit:

http://pleiades.stoa.org/places/347468514

I get insufficient privileges, it's not clear where that's coming from because the permissions assigned to that place should allow me to view it. The traceback is not illuminating, as it indicates a generic Unauthorized error during traversal (at which point authentication has not yet happened). Normally the way to debug this would be to put the instance into debug mode turn on "Verbose Security" logging which would provide more detailed tracebacks on permission issues (at a significant performance cost). Unfortunately, when turned on verbose security on the admin instance, the issue immediately stopped happening on that instance:

http://pleiades.stoa.org:8080/plone/places/347468514

Changing debug mode and security logging should not change whether content can be accessed, so something very fishy appears to be happening. I will continue investigating.

**Comment by alecpm** [comment] 2016-08-21 00:37
Hm, actually it appears changing the debug mode and/or the security verbosity is not what fixed the permission issue. After turning those features back off, I could still access the content. It appears simply restarting the instance allowed me to access the content, which I've confirmed by restarting instance 2 and trying to visit the content there after having failed to access it. I will see if I can reproduce any of these issues now that the instances have been restarted and whatever transient permission issue I was seeing has been cleared.

**Comment by alecpm** [comment] 2016-08-21 00:44
@serviliusahala regarding the connection that appears to be stuck in drafting state, have you visited the "Folder listing of locations, names, and connections" link to edit the connection from the folder listing? Currently, the connection links that appear on the Place page link directly to the connected Place rather than going to the connection, but I have not had any issues visiting the connection object from that link and editing/submitting it. The current display does make modifying newly added connections a bit unintuitive, but it preserves the original (and likely expected) behavior of published connection links. It may make sense to add an "edit" link next to the connections for people with edit permissions to help make the behavior clearer.

I'm still looking into the Insufficient Privileges issue.

**Comment by alecpm** [comment] 2016-08-21 01:09
The permission issue should be fixed now. The issue was that permissions for adding Connections were too limited, such that only the original creator of the containing place or a site admin could create one. Adding Connections is now restricted by the same permissions as adding Locations and Names.

**Comment by alecpm** [comment] 2016-08-21 02:31
In case it wasn't clear this fix is currently deployed both to staging and production.

**Comment by paregorios** [comment] 2016-08-21 15:04
@serviliusahala please give connection creation and editing another try (on the production server) and let us know if you run into any problems.

**Comment by paregorios** [comment] 2016-09-27 20:32
@serviliusahala could you give this a try and let us know how it goes?

**Comment by serviliusahala** [comment] 2016-09-28 19:09
Creating connections has been working ok for me recently and I have not
received that error message related to insufficient privileges for
connections.

thanks,

JAB

# 

Jeffrey A. Becker, Ph.D. RPA
Department of Classical and Near Eastern Studies
Binghamton University - SUNY
jeffrey.becker@gmail.com; 617-877-4484
Twitter: @servilius_ahala https://twitter.com/servilius_ahala

#

**Comment by paregorios** [comment] 2016-09-28 19:09
Thanks @serviliusahala . Closing as resolved.

**Closed as completed by paregorios** 2016-09-28 19:09 UTC
Labels: bug, review, priority: high
