### ISSUE TITLE
Fetch Zotero button shows strange behavior

### ISSUE THREAD

**Issue by atomrab** [isawnyu/pleiades-gazetteer#299] opened 2017-04-03 16:23 UTC
While editing the Arch of Hadrian (https://pleiades.stoa.org/places/235795850) I deleted an irrelevant citation, added the following "see further" citation to Zotero (Adams 1989, https://www.zotero.org/groups/pleiades/items/itemKey/5XQ8KDIN), and -- although the formatted citation field was already filled out -- hit "fetch zotero" to try to guarantee consistency. The page hung for a few seconds, and then refreshed with no change to the fields in that citation. The following citation, however, a see also for Wikipedia, had the short title field filled with the short title of the Adams reference, and the formatted citation field filled with the formatted citation. The Wikipedia link remained in the Access URI field.

**Comment by paregorios** [comment] 2019-03-22 21:34
I will attempt to recreate this behavior in a new, test content item.

**Comment by paregorios** [comment] 2022-10-31 20:47
I have not been able to reproduce this behavior recently, and there have been significant code changes since this ticket was posted, so closing as "magically auto-fixed".

**Closed as not planned by paregorios** 2022-10-31 20:47 UTC
Labels: bug, needs confirmation, candidate AY2022
