### ISSUE TITLE
Error when attempting to paste to errata list

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#274] opened 2017-01-10 19:13 UTC
My attempt to move this unintentional duplicate (https://pleiades.stoa.org/places/509457604) to the errata page (https://pleiades.stoa.org/errata/) by copying and pasting produced an error - 

"We’re sorry, but there seems to be an error…
The error has been logged as entry number 1484075410.10.716284385127."

This procedure is one that I have successfully used in the past, but perhaps it has been superseded by other procedures?

**Comment by paregorios** [comment] 2019-03-22 20:47
I was able successfully to move it just now. And this is still the standard approach (although I'm reminded we could sure use something better). Since I can't reproduce the problem, I'm closing this ticket. Please reopen or open a new one if you run into it again so we can dig deeper.

**Closed as completed by paregorios** 2019-03-22 20:47 UTC
