### ISSUE TITLE
site-map sits and spins

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#84] opened 2016-03-11 23:17 UTC
Clicking on the "site map" link in the header on P4 staging (it's been removed on P3 production), issues a request for ```/sitemap``` that, after a minute or two of unresponsiveness from the server results in:

```
Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 164534
Varnish cache server
```

**Comment by davisagli** [comment] 2016-03-11 23:25
duplicate of #83

**Closed by davisagli** 2016-03-11 23:25 UTC
Labels: bug
