### ISSUE TITLE
Search for place 658576 (Pyramos (river)) returns an error

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#428] opened 2020-06-29 15:37 UTC
A search for the following place (https://pleiades.stoa.org/places/658576) produces this error message:

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 110, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 531, in do_optTag_tal
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Line 28, Column 6
Expression: <PathExpr standard:u'context/@@neighborhood/p_link'>
Names:
{'container': <Place at /plone/places/658576>,
'context': <Place at /plone/places/658576>,
'default': <object object at 0x7f083ee0a520>,
'here': <Place at /plone/places/658576>,
'loop': {},
'nothing': None,
'options': {'args': ()},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f07b039ec00>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/658576/base_view>,
'root': <Application at >,
'template': <FSPageTemplate at /plone/places/658576/base_view>,
'traverse_subpath': [],
'user': <PloneUser 'jbecker'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module pleiades.kml.browser, line 866, in p_link
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.kml.browser, line 840, in geo
Module zope.component.hookable, line 33, in __call__
Module zope.component.hooks, line 104, in adapter_hook
Module pleiades.geographer.geo, line 159, in __init__
Module zope.component.hookable, line 33, in __call__
Module zope.component.hooks, line 104, in adapter_hook
Module pleiades.geographer.geo, line 68, in __init__
Module shapely.geometry.base, line 445, in bounds
Module shapely.geometry.base, line 586, in is_empty
Module shapely.geometry.proxy, line 33, in _geom
Module shapely.geometry.multilinestring, line 120, in geos_multilinestring_from_py
AssertionError

**Comment by paregorios** [comment] 2020-06-30 13:21
I have reproduced the error as follows:

1. Login to Pleiades  (NB: I have been **unable** to reproduce this error while browsing anonymously).
2. Navigate to https://pleiades.stoa.org/places/658576
3. Observe the traceback provided by @serviliusahala, above.

Since this error is only occurring for authenticated users, I suspect it is related to bad/damaged content (i.e., a location, name, or connection)  that is in "drafting" or "pending" state. I will investigate.

**Comment by paregorios** [comment] 2020-06-30 13:22
It's a damaged Location: https://pleiades.stoa.org/places/658576/ceyhan

**Comment by paregorios** [comment] 2020-06-30 13:24
This appears to be a "zombie location" a la #337

**Comment by paregorios** [comment] 2020-06-30 13:28
Zombie connection has been removed via the ZMI as outlined for prior cases in nos. #336 and #337. @serviliusahala if this now works for you, please close this ticket. We will keep the other tickets open pending an opportunity to try to find out why this is still happening despite previous developer work on the problem.

**Closed as completed** 2020-10-26 17:23 UTC
Labels: bug, review, priority: high
