### ISSUE TITLE
add more precise date fields to connections - 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#358] opened 2019-03-01 15:12 UTC
From @rmhorne via email:

> Out of curiosity, how difficult would it be to add two input [boxes] below the current date selector that are constrained by the period selected? For instance, if the Hellenistic era is selected, that the start date and end date fields are pre-populated by the current start / end values for that period, which I can then modify as needed. In terms of connections (and even base places), I think this level of granularity is needed.

**Comment by paregorios** [comment] 2019-03-22 17:52
So, would two additional date data(!!) be sufficient? E.G.:

 - not before
 - not after

Caveats:
 - both labeled to be "proleptic Julian dates prior to establishment of the Gregorian calendar" vel sim. 
 - values constrained by the upper and lower bounds of periods assigned to the context connection? it would throw an error on attempted save if that principle were violated

other concerns @rmhorne @atomrab @serviliusahala ?

**Comment by serviliusahala** [comment] 2019-03-22 18:08
I think having terminus ante quem and terminus post quem options would be great - in many places we could radically narrow the chronology that the gazetteer surfaces.

**Comment by rmhorne** [comment] 2019-03-22 19:49
I think the solution offered by @paregorios (and seconded by @serviliusahala) would work - give a general time frame and the ability to give custom terminus ante quem and terminus post quem options within that frame (with an error / warning if you are violating the time bounds).

**Comment by atomrab** [comment] 2019-03-25 15:44
This is actually excellent timing, because PeriodO has both a developer working on Pleiades integration and some extra money for development that we could use to expand the Pleiades mandate. I think I see two different functionalities here: one is to choose a period and then refine its dates for a particular site (eg one that's destroyed halfway through), and the other is to limit the list of period options available in a given case by selecting a date range in advance. I think both are useful; the developer and I had actually already done the latter for another platform that was working with the PeriodO and Pleiades gazetteers. I will communicate about technical next steps with @paregorios by email.

**Comment by atomrab** [comment] 2019-03-25 18:11
Oh, also: 

> * both labeled to be "proleptic Julian dates prior to establishment of the Gregorian calendar" vel sim.

PeriodO is using proleptic Gregorian dates according to the ISO8601 standard, rather than proleptic Julian dates, which I know are preferred by the Classics community. For dates expressed only in years, as is usually the case for ancient periods, this won't usually make a difference, but I just thought it was worth mentioning.

**Comment by paregorios** [comment] 2019-08-26 15:14
As a Pleiades contributor user, I can add date information to ```connections``` as follows:

 - "not before" field (signed integer) 
 - "not after" field (signed integer)

Validation:

 - ensure values are signed integers or None
 - 0 is not a valid value
 - if both fields contain integers, ensure not_before <= not_after
 - values constrained by the upper and lower bounds of time period(s) assigned to the context ```connection```

UI:
 - both labeled to be "proleptic Julian dates prior to establishment of the Gregorian calendar" vel sim.

**Comment by cguardia** [comment] 2019-08-29 06:03
- [x] Add text fields for not before and not after.
- [x] Add validator for limits.
- [ ] Tweak view to show upper/lower meetings and new fields correctly.

**Comment by cguardia** [comment] 2019-09-07 08:28
@paregorios forgot to remind you today that you were going to give me an idea of what the UI for this would be. A simple mock-up in this ticket will do.

**Comment by cguardia** [comment] 2019-09-08 06:35
@paregorios anyway, I put what I have on staging for you to review. I believe it does what is needed, but might need to reword descriptions.

**Comment by paregorios** [comment] 2019-09-09 21:33
I cannot review this change until staging is working again. It is currently timing out.

**Comment by paregorios** [comment] 2019-09-10 11:15
The behaviors on this look great. Please modify the UI as follows:

- Put the "temporal attestations" widget before these two date fields
- Add a heading that reads "Temporal Constraints: proleptic Julian years prior to establishment of the Gregorian calendar"

So, the relevant portion of the base view should look like this:

---

**Association Certainty:**
Certain

**Temporal attestations:**
- Early Dynastic Egypt (2950-2670 BCE/BC) (confident)

**Temporal Constraints:**
*Proleptic Julian years prior to establishment of the Gregorian calendar*

Not before:
-2950

Not after:
-2670

**References:**

---

**Comment by cguardia** [comment] 2019-09-12 07:36
This is on staging.

**Comment by paregorios** [comment] 2019-09-12 10:23
This looks good in the base view. Could we also surface the same UI modifications in the add/edit form?

**Comment by cguardia** [comment] 2019-09-12 17:24
On staging again. The only issue is that there's no line break between the title and description in edit mode. That's not easy to fix without changing the whole thing and making custom edit and view forms. Since we are out of time, I don't think we can do that.

**Comment by cguardia** [comment] 2020-11-19 01:45
@paregorios could we start this round with a review of what is on staging and go from there? I just put it there.

**Comment by paregorios** [comment] 2020-11-19 12:29
@cguardia I think that's a good idea, but I am not seeing it at pleiades.jazkarta.com. Can you check with @alecpm and see if you are both using the same branches and approach for deployment there? I think he's using isawnyu/PleiadesEntity:master for updates to pleiades.jazkarta.com since the machine at pleiades.jazkarta.com is going to become the production server soon and then tummy will retire the one that's currently called pleiades.stoa.org and I will update DNS accordingly. It looks to me like isawnyu/PleiadesEntity/issues/358 has been merged to "staging" but not to "master".

**Comment by paregorios** [comment] 2020-11-19 18:41
@cguardia I'm seeing a traceback after adding integers to the two fields on the connection at https://pleiades.jazkarta.com/places/874299107/423025:

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
    Module Products.CMFFormController.BaseControllerPageTemplate, line 26, in _call
    Module Products.CMFFormController.FormController, line 384, in validate
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.CMFFormController.FSControllerValidator, line 58, in __call__
    Module Products.CMFFormController.Script, line 145, in __call__
    Module Products.CMFCore.FSPythonScript, line 127, in __call__
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.PythonScripts.PythonScript, line 344, in _exec
    Module script, line 6, in validate_base
    <FSControllerValidator at /plone/places/874299107/423025/validate_base>
    Line 6
    Module Products.Archetypes.BaseObject, line 487, in validate
    Module Products.Archetypes.Schema, line 596, in validate
    Module Products.Archetypes.ClassGen, line 66, in generatedEditAccessor

AttributeError: getRaw 
```

**Comment by cguardia** [comment] 2020-11-19 19:01
Taking a look now.

**Comment by alecpm** [comment] 2020-11-19 21:48
These errors should be fixed now. This was a blocker for reproducing: #344

**Comment by paregorios** [comment] 2020-11-20 11:33
This looks good. Please merge to master and close as resolved.

**Comment by cguardia** [comment] 2020-11-20 18:09
This has been merged to master.

**Closed as completed by cguardia** 2020-11-20 18:09 UTC
Labels: enhancement, priority: high, candidate AY2020/21
